### ISSUE TITLE
Rename to something with docs / documentation

### ISSUE THREAD

**Issue by alexschroeter** [arkitektio/arkitektio.github.io#7]
I would probably rename this repository to make more clear what is inside. Although if you are familiar with github.io it is fairly common to host the documentation there given we want to appeal to a more general audience of users I think the documentation should be named as such.

Here are some ideas with the 'arkitektio-docs' being my favorite:
- [arkitekt|arkitektio]-[docs|documentation]
- documentation

**Comment by jhnnsrs** [comment]
Agreed with the general idea. But I think it's a requirement  of GitHub to let this be hosted on the top level path (otherwise it would be arkitektio.github.io/repo-name). Also this would then break the arkitekt.live forwarding. It's a bit annoying..

**Comment by alexschroeter** [comment]
Ok, I understand. In that case, I would keep it like this until we want to host an arkitekt instance and the CI can just upload to the webserver there.

I will close this as a won't do but want to make this part of a discussion on when to offer a hosted service.

**Comment by alexschroeter** [comment]
Alternatively we could use something like netlify to host the documentation. I believe this would be free initially and would allow renaming the repository to something more meaningful.
